# Generated by Django 3.2.21 on 2023-10-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0194_alter_problem_is_guest_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='is_guest_private',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Private to guest'),
        ),
    ]
