# Generated by Django 3.2.21 on 2023-11-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0195_alter_problem_is_guest_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='from_ghost_account',
            field=models.BooleanField(default=False, verbose_name='from ghost account'),
        ),
    ]
