# Generated by Django 3.2.21 on 2023-11-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0196_submission_from_ghost_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='from_ghost_account',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='from ghost account'),
        ),
    ]
