# Generated by Django 3.2.21 on 2023-12-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0197_alter_submission_from_ghost_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='is_guest_private',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Private to guest'),
        ),
    ]
